### ISSUE TITLE
Add a generator to init a webpackage

### ISSUE THREAD

**Issue by hrbu** [cubbles/generator-cubbles#2]
The new way developing a webpackage is heavily based on top of npm packages. The steps to create a new webpackage is as follows:
1. run `npm init` ... to setup the `package.json`
2. run `npm i -D yo generator-cubbles` to install the latest versions of `yeoman` and the `generator-cubbles`
3. run `npx yo cubbles:init` to init the package as a cubbles webpackage (folder structure and basic files)
4. run `npx yo cubbles:elementary` to scaffold an elementary
5. run `npx yo cubbles:compound` to scaffold an compound

# Task 
Add the `cubbles:init` generator to init a webpackage.

## AcceptanceCriterias
- [ ] top level configuration files are created (`webpack.config.js`, `.gitignore`, `cubx-uploader-config.dev.json`, ...)
- [ ] top level folders have been created: `src` and `dist`
- [ ] devDependencies have been updated and installed

**Comment by hrbu** [comment]
We decided to not use a generator. Instead we will have a 3 step guide to create a new webpackage based on the [coder-template](https://github.com/cubbles/coder-template).
